# Generated by Django 4.2 on 2023-06-29 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Example Joe, Jane', max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(help_text='joedoe@gmail.com', max_length=254)),
                ('phone_number', models.IntegerField(help_text='0712345678 or +254712345678')),
                ('gender', models.CharField(help_text='male, female, other', max_length=20)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField(auto_now=True)),
                ('order_status', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('order_discount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=350)),
                ('product_price', models.FloatField()),
                ('description', models.TextField()),
                ('product_tax', models.FloatField()),
                ('product_discount', models.FloatField()),
                ('stock', models.IntegerField()),
                ('products_bought', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_weight', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('delivery_cost', models.FloatField()),
                ('shipping_discount', models.FloatField()),
                ('shipping_status', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(help_text='Mpesa(Kenyan phone numbers only), Bank_Transaction, cash on delivery', max_length=250)),
                ('payment_phone', models.IntegerField(help_text='0712345678 or +254712345678')),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shipping')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('coupon_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('offer_discount', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shipping')),
            ],
        ),
    ]
