# Generated by Django 4.2 on 2023-07-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_customer_username_customer_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
