# Generated by Django 4.2 on 2023-08-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_address2_customer_cityorcounty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cityOrcounty',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
    ]
