# Generated by Django 4.2 on 2023-08-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_customer_address_remove_customer_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
    ]
