# Generated by Django 4.2 on 2023-08-29 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0012_alter_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_date', models.DateField(auto_now=True)),
                ('complete', models.BooleanField(default=False)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=350)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('product_tax', models.FloatField()),
                ('stock', models.IntegerField()),
                ('products_bought', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('shipping_code', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('delivery_cost', models.FloatField()),
                ('shipping_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.order')),
            ],
            options={
                'db_table': 'shippingAddress',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(help_text='Mpesa(Kenyan phone numbers only)', max_length=250)),
                ('payment_phone', models.IntegerField(help_text='0712345678 or +254712345678')),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.order')),
            ],
            options={
                'db_table': 'payment_information',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.product')),
            ],
            options={
                'db_table': 'orderItem',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('coupon_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('offer_discount', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.product')),
                ('shippingAddress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.shippingaddress')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_code', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('issue', models.CharField(blank=True, max_length=300, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.order')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
