# Generated by Django 4.2 on 2023-07-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_remove_offer_order_remove_offer_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField(auto_now=True)),
                ('order_status', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('order_discount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=350)),
                ('product_price', models.FloatField()),
                ('product_tax', models.FloatField()),
                ('product_discount', models.FloatField()),
                ('stock', models.IntegerField()),
                ('products_bought', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_weight', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('delivery_cost', models.FloatField()),
                ('shipping_discount', models.FloatField()),
                ('shipping_status', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManagement.order')),
            ],
            options={
                'db_table': 'shipping',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(help_text='Mpesa(Kenyan phone numbers only), Bank_Transaction, cash on delivery', max_length=250)),
                ('payment_phone', models.IntegerField(help_text='0712345678 or +254712345678')),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManagement.order')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.shipping')),
            ],
            options={
                'db_table': 'payment_information',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManagement.product'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('coupon_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('offer_discount', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.product')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.shipping')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_code', models.CharField(max_length=20)),
                ('issue', models.CharField(max_length=300)),
                ('other', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManagement.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productManagement.product')),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productManagement.shipping')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
