# Generated by Django 4.2 on 2023-08-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
