# Generated by Django 4.2 on 2023-08-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
