# Generated by Django 4.2 on 2023-08-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0005_remove_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='shipping',
            new_name='shippingAddress',
        ),
        migrations.AddField(
            model_name='complaints',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='phone_number',
            field=models.IntegerField(blank=True, help_text='0712345678 or +254712345678', null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='issue',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
