# Generated by Django 5.0.1 on 2024-03-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customer_gender'),
        ('productManagement', '0005_alter_offer_offer_discount_alter_order_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='complaints',
            name='order',
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complaint_code',
            field=models.CharField(auto_created=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
