# Generated by Django 5.0.1 on 2024-03-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0006_remove_complaints_gender_remove_complaints_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='delivery_cost',
        ),
    ]
