# Generated by Django 5.0.1 on 2024-03-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0007_remove_shippingaddress_delivery_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
