# Generated by Django 5.0.1 on 2024-03-26 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0008_remove_offer_description_delete_paymentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
