# Generated by Django 5.0.1 on 2024-03-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productManagement', '0009_remove_order_cost_delete_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
